### ISSUE TITLE
USER INPUT ISSUES

### ISSUE THREAD

**Issue by Krish2310** [sayalaruano/AMPredST#1]
Hello there!
  Hope you're doing fine! I have some issues with user input. when I input the defaults through those buttons its working fine. but whenever I give an user input its showing a blank page. Is there any issues with session_state?? of the input field?? How to solve this issue?...

**Comment by sayalaruano** [comment]
Hi @Krish2310! Thanks for the feedback. I was evaluating it and figured out that the error could be because the input only accepts the letters from the 20 amino acids. What input sequence did you try? Do you think it is a good idea to add a warning message when this happens and let the user know about it?

**Comment by Krish2310** [comment]
Hi @sayalaruano! 
Happy to see your response!  I guess it works with the sequences that have >20 or <20 amino acids... I checked it.....  It works well with every sequence. The sequence that I checked is "YKQCHKKGGHCFPKEKICLPPSSDFGKMDCRWRWK" which is in your test amp fasta file. 
Thanks for such a creative application! I found it very useful for my studies!
Here I have attached a screen recording of the issue. 
1. ----> when I give an input sequence and press enter its not showing the results.... but when I click on any of the example sequence button and again input the same sequence afterwards gives the output
2. ----> when I hit the clear input button then pasting a new input sequence, isn't showing the result 
kindly look up to this issue.....

[streamlit-streamlit_app-2022-12-12-16-12-90.webm](https://user-images.githubusercontent.com/120088048/207038130-2b956391-cf07-422b-b58f-5b9e9d868e2a.webm)

**Comment by sayalaruano** [comment]
Hi @Krish2310! I just detected the error, it was because I did not specify the key parameter in the st.sidebar.text_input() widget. I changed it and it seems to be fine now. Please, let me know if everything is ok now. Thank you very much for your feedback!

**Comment by Krish2310** [comment]
Hi @sayalaruano! Thank you so much for the clarification! Yes, It works perfect now! Thank youuuuuu!
